map_type: costmap

obstacle_range: 1.0
raytrace_range: 3.50

transform_tolerance: 1.0

inflation_radius: 0.35


observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
